### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by tommyshelby9121** [VelvetThePanda/SilkBot#13]
Check for user permissions before being able to execute moderation commands. Permissions such as `kick_members` for kicking users `ban_members` for being able to ban members and so on. This should be the first one that the bot should check for.

**Comment by VelvetThePanda** [comment]
This is a rather strange issue I'll have to look into. See [my permission extension method](https://github.com/VelvetThePanda/SilkBot/blob/master/Utilities/PermissionHelper.cs#L10), which is used in the [ban command](https://github.com/VelvetThePanda/SilkBot/blob/master/Commands/Moderation/BanCommand.cs#L27)

**Comment by VelvetThePanda** [comment]
Actually I just notice that command uses the old method of checking perms. This will be fixed soon 👍

**Comment by VelvetThePanda** [comment]
Thank you for pointing this out. The issue has been mentioned in the most recent changelog, and close monitoring will be put in place for any following security issues.
