### ISSUE TITLE
Check if bot has permission 

### ISSUE THREAD

**Issue by tommyshelby9121** [VelvetThePanda/SilkBot#15]
When executing certain commands like kicking or banning users, the bot needs the associated permissions just like the users who execute those commands. So add a check to see if the bot has permission to execute said command. Eg: The bot should check if it has the permission `kick_members` before being able to kick. `Administrator` permission takes precedence on this. However, not all guild owners may want to give a bot `administrator` permissions.

**Comment by VelvetThePanda** [comment]
Silk does actually check for permissions, if you see <prefix>perms. The administrative requirement has been changed to the needed permissions, which can be individually toggled when adding the bot.
