### ISSUE TITLE
Usage Message

### ISSUE THREAD

**Issue by tommyshelby9121** [VelvetThePanda/SilkBot#18]
When a command is executed such as `ban` or `kick`, instead of the bot giving utter silence, maybe replace it with an embed that tells the user how to execute the command. Such as `?ban <user> [reason]` where anything in `<>` is required and anything with-in `[ ]` is optional. This is ofcourse for users with the correct permission.

**Comment by VelvetThePanda** [comment]
You see the problem with this is that some commands actually do provide feedback when you pass no parameters, if you've ever bothered to look at the source. Also see <prefix>help <command>

**Comment by tommyshelby9121** [comment]
You realize I don't know jack shit about C# right?
