### ISSUE TITLE
SAR doesn't check for an empty list of roles when no server config exists

### ISSUE THREAD

**Issue by TrueBoxGuy** [VelvetThePanda/SilkBot#21]
The response the command !sar gives is different when no server config exists, and is sometimes incorrect. 

Without server config: 
![image](https://user-images.githubusercontent.com/17554188/90339929-4b7d4c00-dfec-11ea-95e3-c3466cb8ab82.png)
With server config: 
![image](https://user-images.githubusercontent.com/17554188/90339921-402a2080-dfec-11ea-8989-4b67f84976f2.png)

**Comment by VelvetThePanda** [comment]
Never fixed this dunno why it got closed.
