### ISSUE TITLE
Minor typos in the repo. 

### ISSUE THREAD

**Issue by TrueBoxGuy** [VelvetThePanda/SilkBot#23]
I found three minor typos in the repo: 

- Authentication is misspelled in the auth command. 
- A frivolous full stop exists in the `!repo` command.  ![image](https://user-images.githubusercontent.com/17554188/90340154-00fccf00-dfee-11ea-9ac0-ee3811acf8b9.png)
- The examples for the `!DiceRoll` command use `!diceroll`, but commands are case-sensitive.

**Comment by VelvetThePanda** [comment]
I'm only slapping won't fix on here because adding erroneous punctuation would break any bot. I'll fix the typo, though.
